version: '3.8'

services:
  petrolis-webapp:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Firebase principale (dmprojectnew)
      NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyA2rUtbVrUq68JmnAKJ8J0g1mvNoIg1GHs"
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "dmprojectnew.firebaseapp.com"
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: "dmprojectnew"
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "dmprojectnew.firebasestorage.app"
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "920921649335"
      NEXT_PUBLIC_FIREBASE_APP_ID: "1:660509531035:web:aa5796eda30fb7f39edf3e"
      
      # Firebase dedicato alle immagini (petrolis-cd75b)
      NEXT_PUBLIC_STORAGE_PUBLIC_API_KEY: "AIzaSyChev6cBb77QU1TzyK4txnYLnkScbDMxW0"
      NEXT_PUBLIC_STORAGE_PUBLIC_AUTH_DOMAIN: "petrolis-cd75b.firebaseapp.com"
      NEXT_PUBLIC_STORAGE_PUBLIC_PROJECT_ID: "petrolis-cd75b"
      NEXT_PUBLIC_STORAGE_PUBLIC_BUCKET: "petrolis-cd75b.firebasestorage.app"
      NEXT_PUBLIC_STORAGE_PUBLIC_MESSAGING_SENDER_ID: "31005220155"
      NEXT_PUBLIC_STORAGE_PUBLIC_APP_ID: "1:31005220155:web:6668d46b9ba31c5e65eb1e"
      
      # OpenAI API Key
      OPENAI_API_KEY: "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"
      
      # ImgBB API Key (legacy, non più utilizzata ma mantenuta per compatibilità)
      NEXT_PUBLIC_IMGBB_API_KEY: "fac33993006884896dacf85c5ecd5f39"
      
      # Configurazione Node.js
      NODE_ENV: "production"
      PORT: "3000"
    restart: unless-stopped
    container_name: petrolis-webapp
    networks:
      - petrolis-network

networks:
  petrolis-network:
    external: false 